
CREATE DATABASE aanchol_db;
USE aanchol_db;

CREATE TABLE divisions (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    name_en VARCHAR(100) NOT NULL
);

CREATE TABLE districts (
    id INT PRIMARY KEY AUTO_INCREMENT,
    division_id INT,
    name VARCHAR(100) NOT NULL,
    name_en VARCHAR(100) NOT NULL,
    FOREIGN KEY (division_id) REFERENCES divisions(id)
);

CREATE TABLE upazilas (
    id INT PRIMARY KEY AUTO_INCREMENT,
    district_id INT,
    name VARCHAR(100) NOT NULL,
    name_en VARCHAR(100) NOT NULL,
    FOREIGN KEY (district_id) REFERENCES districts(id)
);


CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    division_id INT,
    district_id INT,
    upazila_id INT,
    detailed_address TEXT,
    role ENUM('admin', 'customer') DEFAULT 'customer',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (division_id) REFERENCES divisions(id),
    FOREIGN KEY (district_id) REFERENCES districts(id),
    FOREIGN KEY (upazila_id) REFERENCES upazilas(id)
);


INSERT INTO divisions (name, name_en) VALUES
('ঢাকা', 'Dhaka'),
('চট্টগ্রাম', 'Chittagong'),
('খুলনা', 'Khulna'),
('রাজশাহী', 'Rajshahi'),
('বরিশাল', 'Barisal'),
('সিলেট', 'Sylhet'),
('রংপুর', 'Rangpur'),
('ময়মনসিংহ', 'Mymensingh');

INSERT INTO districts (division_id, name, name_en) VALUES
(1, 'ঢাকা', 'Dhaka'),
(1, 'গাজীপুর', 'Gazipur'),
(1, 'নারায়ণগঞ্জ', 'Narayanganj'),
(1, 'টাঙ্গাইল', 'Tangail'),
(1, 'মানিকগঞ্জ', 'Manikganj'),
(1, 'মুন্সিগঞ্জ', 'Munshiganj'),
(1, 'রাজবাড়ী', 'Rajbari'),
(1, 'শরিয়তপুর', 'Shariatpur'),
(2, 'চট্টগ্রাম', 'Chittagong'),
(2, 'কক্সবাজার', 'Coxs Bazar'),
(2, 'খাগড়াছড়ি', 'Khagrachhari'),
(2, 'রাঙ্গামাটি', 'Rangamati'),
(2, 'নোয়াখালী', 'Noakhali'),
(2, 'ফেনী', 'Feni'),
(2, 'লক্ষ্মীপুর', 'Lakshmipur'),
(2, 'কুমিল্লা', 'Cumilla'),
(3, 'খুলনা', 'Khulna'),
(3, 'বাগেরহাট', 'Bagerhat'),
(3, 'যশোর', 'Jessore'),
(3, 'সাতক্ষীরা', 'Satkhira'),
(3, 'পিরোজপুর', 'Pirojpur'),
(3, 'ঝালকাটি', 'Jhalokati'),
(3, 'বরিশাল', 'Barisal'),
(3, 'ভোলা', 'Bhola'),
(3, 'পটুয়াখালী', 'Patuakhali'),
(4, 'রাজশাহী', 'Rajshahi'),
(4, 'নাটোর', 'Natore'),
(4, 'নওগাঁ', 'Nawabganj'),
(4, 'পাবনা', 'Pabna'),
(4, 'বগুড়া', 'Bogra'),
(4, 'সিরাজগঞ্জ', 'Sirajganj'),
(5, 'বরিশাল', 'Barisal'),
(5, 'পটুয়াখালী', 'Patuakhali'),
(5, 'ভোলা', 'Bhola'),
(5, 'ঝালকাটি', 'Jhalokati'),
(5, 'পিরোজপুর', 'Pirojpur'),
(6, 'সিলেট', 'Sylhet'),
(6, 'সিলেট', 'Sylhet'),
(6, 'সুনামগঞ্জ', 'Sunamganj'),
(6, 'মৌলভীবাজার', 'Moulvibazar'),
(6, 'হবিগঞ্জ', 'Habiganj'),
(7, 'রংপুর', 'Rangpur'),
(7, 'দিনাজপুর', 'Dinajpur'),
(7, 'থাকুরগাঁও', 'Thakurgaon'),
(7, 'পঞ্চগড়', 'Panchagarh'),
(7, 'কুড়িগ্রাম', 'Kurigram'),
(7, 'গাইবান্ধা', 'Gaibandha'),
(7, 'লালমনিরহাট', 'Lalmonirhat'),
(8, 'ময়মনসিংহ', 'Mymensingh'),
(8, 'ময়মনসিংহ', 'Mymensingh'),
(8, 'জামালপুর', 'Jamalpur'),
(8, 'শেরপুর', 'Sherpur'),
(8, 'নেত্রকোণা', 'Netrokona');

INSERT INTO upazilas (district_id, name, name_en) VALUES
(1, 'ঢাকা সদর', 'Dhaka Sadar'),
(1, 'মিরপুর', 'Mirpur'),
(1, 'উত্তরা', 'Uttara'),
(1, 'ধানমন্ডি', 'Dhanmondi'),
(1, 'মোহাম্মদপুর', 'Mohammadpur'),
(1, 'আদাবর', 'Adabor'),
(1, 'বনশ্রী', 'Banasree'),
(1, 'গুলশান', 'Gulshan'),
(1, 'বাংলামোটর', 'Banglmotor'),
(1, 'কেরানীগঞ্জ', 'Keraniganj'),
(1, 'ডোহার', 'Dohar'),
(2, 'গাজীপুর সদর', 'Gazipur Sadar'),
(2, 'কালীগঞ্জ', 'Kaliakair'),
(2, 'কাপাসিয়া', 'Kapashia'),
(2, 'শ্রীপুর', 'Sripur'),
(2, 'নারসিংদী', 'Narsingdi'),
(3, 'নারায়ণগঞ্জ সদর', 'Narayanganj Sadar'),
(3, 'সোনারগাঁ', 'Sonargaon'),
(3, 'রূপগঞ্জ', 'Rupganj'),
(3, 'সিদ্ধিরগঞ্জ', 'Siddhirganj'),
(4, 'টাঙ্গাইল সদর', 'Tangail Sadar'),
(4, 'মধুপুর', 'Madhupur'),
(4, 'কালিহাতি', 'Kalihat'),
(4, 'গাজারিয়া', 'Gaziaria'),
(4, 'দেলদুয়ার', 'Delduar'),
(4, 'ঘাটাইল', 'Ghatail'),
(4, 'শাহজাদপুর', 'Shahzadpur'),
(4, 'বাসাইল', 'Basail'),
(4, 'নাগরপুর', 'Nagarpur'),
(5, 'মানিকগঞ্জ সদর', 'Manikganj Sadar'),
(5, 'সাটিয়া', 'Satia'),
(5, 'সিঙ্গাইর', 'Singair'),
(5, 'ঘিওর', 'Ghior'),
(5, 'দৌলতপুর', 'Daulatpur'),
(5, 'শিবালয়', 'Shibalay'),
(5, 'পাংশা', 'Pangsha'),
(6, 'মুন্সিগঞ্জ সদর', 'Munshiganj Sadar'),
(6, 'গজারিয়া', 'Gaziaria'),
(6, 'শ্রীনগর', 'Srinagar'),
(6, 'টিটাগড়', 'Titagarh'),
(6, 'লৌহজং', 'Lohajang'),
(6, 'রাজৈর', 'Rajair'),
(7, 'রাজবাড়ী সদর', 'Rajbari Sadar'),
(7, 'কালুখালী', 'Kalukhali'),
(7, 'বালিয়াকান্দি', 'Baliakandi'),
(8, 'শরিয়তপুর সদর', 'Shariatpur Sadar'),
(8, 'নরিঙ্গল', 'Nariangal'),
(8, 'জাজিরা', 'Zajira'),
(8, 'পালং', 'Paling'),
(9, 'চট্টগ্রাম সদর', 'Chittagong Sadar'),
(9, 'পটিয়া', 'Patiya'),
(9, 'রাউজান', 'Rauzan'),
(9, 'সন্দ্বীপ', 'Sandip'),
(9, 'হাটহাজারি', 'Hathazari'),
(9, 'রাঙ্গুনিয়া', 'Rangunia'),
(9, 'বোয়ালখালী', 'Boalkhali'),
(9, 'ফটিকছড়ি', 'Fatikchhari'),
(9, 'বন্দরবান', 'Bandarban'),
(9, 'কুমিল্লা', 'Cumilla'),
(10, 'কক্সবাজার সদর', 'Coxs Bazar Sadar'),
(10, 'টেকনাফ', 'Teknaf'),
(10, 'উখিয়া', 'Ukhia'),
(10, 'মহেশখালী', 'Maheshkhali'),
(10, 'চকরিয়া', 'Chakaria'),
(10, 'রামু', 'Ramu'),
(11, 'খাগড়াছড়ি সদর', 'Khagrachhari Sadar'),
(11, 'দীঘিনালা', 'Dighinala'),
(11, 'মাতিরাঙ্গা', 'Matiranga'),
(11, 'রাঙ্গামাটি', 'Rangamati'),
(11, 'পানছালাইহ', 'Panchhalain'),
(12, 'রাঙ্গামাটি সদর', 'Rangamati Sadar'),
(12, 'কাপ্তাই', 'Kaptai'),
(12, 'বাঘাইছড়ি', 'Baghaichhari'),
(12, 'বড়হাতিয়া', 'Borhatia'),
(12, 'লংগদু', 'Longdu'),
(12, 'নানিয়াছড়', 'Naniachara'),
(13, 'নোয়াখালী সদর', 'Noakhali Sadar'),
(13, 'কোম্পানীগঞ্জ', 'Companiganj'),
(13, 'চট্টাই', 'Chatai'),
(13, 'সেনবাগ', 'Senbag'),
(13, 'বেগমগঞ্জ', 'Begumganj'),
(13, 'সোনাইমারী', 'Sonamairy'),
(14, 'ফেনী সদর', 'Feni Sadar'),
(14, 'সোনাগাজী', 'Sonagazi'),
(14, 'ফুলছেড়ি', 'Fulchhari'),
(14, 'চৌদ্দগ্রাম', 'Chhagalnaiya'),
(14, 'পরাগলছড়', 'Parshuram'),
(15, 'লক্ষ্মীপুর সদর', 'Lakshmipur Sadar'),
(15, 'কমলনগর', 'Kamalnagar'),
(15, 'রাইপুর', 'Raipur'),
(15, 'রামগঞ্জ', 'Ramganj'),
(16, 'কুমিল্লা সদর', 'Cumilla Sadar'),
(16, 'দাউদকান্দি', 'Daudkandi'),
(16, 'লাকসাম', 'Laksam'),
(16, 'চান্দিনা', 'Chandina'),
(16, 'মেঘনা', 'Meghna'),
(16, 'ব্রাহ্মণপাড়া', 'Brahmanpara'),
(16, 'বুড়িচং', 'Burichong'),
(16, 'মনোহরগঞ্জ', 'Monoharganj'),
(16, 'নিউজয়', 'Niyazganj'),
(17, 'খুলনা সদর', 'Khulna Sadar'),
(17, 'খালিশপুর', 'Khalishpur'),
(17, 'কুষ্টিয়া', 'Kushtia'),
(17, 'ডুমুরিয়া', 'Dumuria'),
(17, 'ফকিরহাট', 'Fakhirhat'),
(18, 'বাগেরহাট সদর', 'Bagerhat Sadar'),
(18, 'চিতলমারি', 'Chitmari'),
(18, 'কালিগঞ্জ', 'Kaliganj'),
(18, 'মোরেলগঞ্জ', 'Morelganj'),
(18, 'রামপাল', 'Rampal'),
(19, 'যশোর সদর', 'Jessore Sadar'),
(19, 'অভয়নগর', 'Abhaynagar'),
(19, 'বাওয়ানিয়া', 'Baownia'),
(19, 'চৌগাছা', 'Chougacha'),
(19, 'মনিরামপুর', 'Manirampur'),
(19, 'শার্শা', 'Sharsha'),
(20, 'সাতক্ষীরা সদর', 'Satkhira Sadar'),
(20, 'ডেমরা', 'Debra'),
(20, 'কালারোয়া', 'Kaalaroa'),
(20, 'শ্যামনগর', 'Shyamnagar'),
(20, 'তালা', 'Tala'),
(21, 'পিরোজপুর সদর', 'Pirojpur Sadar'),
(21, 'নেছারাবাদ', 'Nesarabad'),
(21, 'স্বরূপকাঠি', 'Swarupkati'),
(21, 'মাতারবাড়ি', 'Matarbari'),
(21, 'ইন্দুরকানি', 'Indurkani'),
(22, 'ঝালকাটি সদর', 'Jhalokati Sadar'),
(22, 'কাঠালিয়া', 'Kathalia'),
(22, 'নাজিরগঞ্জ', 'Nazirgang'),
(23, 'বরিশাল সদর', 'Barisal Sadar'),
(23, 'বাকেরগঞ্জ', 'Bakerganj'),
(23, 'গৌরনদী', 'Gournadi'),
(23, 'ঝালকাটি', 'Jhalokati'),
(23, 'উজিরপুর', 'Ujirpur'),
(23, 'মেহেন্দিগঞ্জ', 'Mehendiganj'),
(23, 'বটিয়াঘাটা', 'Batiagata'),
(24, 'ভোলা সদর', 'Bhola Sadar'),
(24, 'তজুমদ্দিন', 'Tazumuddin'),
(24, 'দক্ষিণ তালপট্টি', 'Dakhin Talpatti'),
(24, 'চরফ্যাশন', 'Charfation'),
(24, 'লালমোহন', 'Lalmohan'),
(25, 'পটুয়াখালী সদর', 'Patuakhali Sadar'),
(25, 'কোলাহল', 'Kolapara'),
(25, 'মিরজুগঞ্জ', 'Mirzaganj'),
(25, 'দশমিনা', 'Dashmina'),
(25, 'গালছিরা', 'Galtira'),
(26, 'রাজশাহী সদর', 'Rajshahi Sadar'),
(26, 'মোহনপুর', 'Mohanpur'),
(26, 'চাঁপাইনবাবগঞ্জ', 'Chapainawabganj'),
(26, 'তানোর', 'Tanor'),
(26, 'পবা', 'Poba'),
(26, 'বাঘা', 'Bagha'),
(26, 'নাটোরবহর', 'Natore'),
(27, 'নাটোর সদর', 'Natore Sadar'),
(27, 'গুরুদাসপুর', 'Gurudaspura'),
(27, 'নওগাঁ', 'Nawabganj'),
(27, 'সিংগা', 'Singa'),
(28, 'নওগাঁ সদর', 'Nawabganj Sadar'),
(28, 'আত্রাই', 'Atrai'),
(28, 'মান্দা', 'Manda'),
(28, 'পোরাণ', 'Poran'),
(28, 'ধনবাড়ি', 'Dhanvari'),
(28, 'রানীনগর', 'Raninagar'),
(29, 'পাবনা সদর', 'Pabna Sadar'),
(29, 'আটঘরিয়া', 'Atgharia'),
(29, 'ভাঙ্গুড়া', 'Bhangura'),
(29, 'চাটমোহর', 'Chatmohar'),
(29, 'ফরিদপুর', 'Faridpur'),
(29, 'সাঁথিয়া', 'Sathia'),
(29, 'সুজানগর', 'Sujanagar'),
(30, 'বগুড়া সদর', 'Bogra Sadar'),
(30, 'আদমদীঘি', 'Adamdighi'),
(30, 'ধুনট', 'Dhunot'),
(30, 'গাবতলী', 'Gabtali'),
(30, 'কাহালু', 'Kahalu'),
(30, 'নন্দীগ্রাম', 'Nandigram'),
(30, 'শাজাদপুর', 'Shajahanpur'),
(30, 'সোহাগ', 'Souhag'),
(31, 'সিরাজগঞ্জ সদর', 'Sirajganj Sadar'),
(31, 'উল্লাপাড়া', 'Ullapara'),
(31, 'পাঁচবিবি', 'Panchbibi'),
(31, 'ধামইরহাট', 'Dhamoirhat'),
(31, 'কাজিহা', 'Kaziha'),
(31, 'বেলকুচি', 'Belkuci'),
(31, 'রায়গঞ্জ', 'Rayiganj'),
(31, 'তাড়াশ', 'Tarash'),
(32, 'বরিশাল সদর', 'Barisal Sadar'),
(32, 'বাকেরগঞ্জ', 'Bakerganj'),
(32, 'গৌরনদী', 'Gournadi'),
(32, 'ঝালকাটি', 'Jhalokati'),
(32, 'উজিরপুর', 'Ujirpur'),
(32, 'মেহেন্দিগঞ্জ', 'Mehendiganj'),
(32, 'বটিয়াঘাটা', 'Batiagata'),
(33, 'পটুয়াখালী সদর', 'Patuakhali Sadar'),
(33, 'কোলাহল', 'Kolapara'),
(33, 'মিরজুগঞ্জ', 'Mirzaganj'),
(33, 'দশমিনা', 'Dashmina'),
(33, 'গালছিরা', 'Galtira'),
(34, 'ভোলা সদর', 'Bhola Sadar'),
(34, 'তজুমদ্দিন', 'Tazumuddin'),
(34, 'দক্ষিণ তালপট্টি', 'Dakhin Talpatti'),
(34, 'চরফ্যাশন', 'Charfation'),
(34, 'লালমোহন', 'Lalmohan'),
(35, 'ঝালকাটি সদর', 'Jhalokati Sadar'),
(35, 'কাঠালিয়া', 'Kathalia'),
(35, 'নাজিরগঞ্জ', 'Nazirgang'),
(36, 'পিরোজপুর সদর', 'Pirojpur Sadar'),
(36, 'নেছারাবাদ', 'Nesarabad'),
(36, 'স্বরূপকাঠি', 'Swarupkati'),
(36, 'মাতারবাড়ি', 'Matarbari'),
(36, 'ইন্দুরকানি', 'Indurkani'),
(37, 'সিলেট সদর', 'Sylhet Sadar'),
(37, 'বিয়ানীবাজার', 'Beanibazar'),
(37, 'দক্ষিণ সুরমা', 'Dakhin Surma'),
(37, 'গোয়াইনঘাট', 'Gowainghat'),
(37, 'জৈন্তিয়াপুর', 'Jaintiapur'),
(38, 'সুনামগঞ্জ সদর', 'Sunamganj Sadar'),
(38, 'দিরাই', 'Dirai'),
(38, 'তাহিরপুর', 'Tahirpur'),
(38, 'ছাতক', 'Chattak'),
(39, 'মৌলভীবাজার সদর', 'Moulvibazar Sadar'),
(39, 'কুলাউড়া', 'Kulaura'),
(39, 'বড়লেখা', 'Barlekha'),
(39, 'জুরি', 'Juri'),
(39, 'রাজনগর', 'Rajanar'),
(40, 'হবিগঞ্জ সদর', 'Habiganj Sadar'),
(40, 'বানিয়াচং', 'Baniyachang'),
(40, 'লাখাই', 'Lakhaii'),
(40, 'মাধবপুর', 'Madhobpur'),
(40, 'অজিমনগর', 'Azimganj'),
(41, 'রংপুর সদর', 'Rangpur Sadar'),
(41, 'গঙ্গাচড়া', 'Gangachara'),
(41, 'মিঠাপুকুর', 'Mithapukur'),
(41, 'পীরগঞ্জ', 'Pirganj'),
(41, 'তারাগঞ্জ', 'Taraganj'),
(42, 'দিনাজপুর সদর', 'Dinajpur Sadar'),
(42, 'বিরল', 'Biral'),
(42, 'খানসামা', 'Khansama'),
(42, 'ফুলবাড়ি', 'Fulbari'),
(42, 'গাইবান্ধা', 'Gaibandha'),
(42, 'নবাবগঞ্জ', 'Nababganj'),
(43, 'থাকুরগাঁও সদর', 'Thakurgaon Sadar'),
(43, 'রানীসংকৈল', 'Ranisankail'),
(43, 'বালিয়াডাঙ্গি', 'Baliadangi'),
(44, 'পঞ্চগড় সদর', 'Panchagarh Sadar'),
(44, 'আদিতমারী', 'Aditmarhi'),
(44, 'বোদা', 'Boda'),
(44, 'দেবীগঞ্জ', 'Debiganj'),
(45, 'কুড়িগ্রাম সদর', 'Kurigram Sadar'),
(45, 'বাগদা', 'Bagda'),
(45, 'চিলমারী', 'Chilimaari'),
(45, 'রৌমারী', 'Rowmari'),
(45, 'নাগেশ্বরী', 'Nageshwari'),
(45, 'ভুরুঙ্গামারী', 'Bhurungamari'),
(46, 'গাইবান্ধা সদর', 'Gaibandha Sadar'),
(46, 'সাদুল্লাপুর', 'Sadullapur'),
(46, 'ফুলছেড়ি', 'Fulchhari'),
(46, 'পালনপুর', 'Palnpur'),
(46, 'জঙ্গলবাড়ি', 'Jungalbari'),
(47, 'লালমনিরহাট সদর', 'Lalmonirhat Sadar'),
(47, 'হাতীবান্ধা', 'Hatibandhha'),
(47, 'পাটগ্রাম', 'Patgram'),
(47, 'আদমদীঘি', 'Adamdighi'),
(48, 'ময়মনসিংহ সদর', 'Mymensingh Sadar'),
(48, 'ফুলপুর', 'Fulpur'),
(48, 'গফরগাঁও', 'Gafargaon'),
(48, 'ঈশ্বরগঞ্জ', 'Ishwarganj'),
(48, 'কিশোরগঞ্জ', 'Kishoreganj'),
(48, 'নান্দাইল', 'Nandail'),
(48, 'দেওয়ানগঞ্জ', 'Dewanganj'),
(48, 'আউশগাঁও', 'Aushgao'),
(49, 'জামালপুর সদর', 'Jamalpur Sadar'),
(49, 'মেলন্দহ', 'Melendah'),
(49, 'ইসলামপুর', 'Islampur'),
(49, 'সরিসাব', 'Sarisab'),
(49, 'বকশীগঞ্জ', 'Bakshiganj'),
(50, 'শেরপুর সদর', 'Sherpur Sadar'),
(50, 'নালিতাবাড়ি', 'Nalitabari'),
(50, 'জগদ্দল', 'Jagdal'),
(50, 'পলাশবাড়ি', 'Polashbari'),
(51, 'নেত্রকোণা সদর', 'Netrokona Sadar'),
(51, 'কেন্দুয়া', 'Kendua'),
(51, 'মোহনগঞ্জ', 'Mohanganj'),
(51, 'পূর্বমেঘালয়', 'Purba Meghalai'),
(51, 'দূর্গাপুর', 'Durgapur'),
(51, 'বারহাট্টা', 'Barhatta');


INSERT INTO users (name, email, password, phone, role) VALUES
('Admin', 'admin@aanchol.com', '$2y$10$YourHashedPasswordHere', NULL, 'admin');


CREATE TABLE categories (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    slug VARCHAR(50) UNIQUE NOT NULL
);


CREATE TABLE products (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(200) NOT NULL,
    description TEXT,
    price DECIMAL(10,2) NOT NULL,
    category_id INT,
    stock INT DEFAULT 0,
    image VARCHAR(255),
    status ENUM('active', 'inactive') DEFAULT 'active',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (category_id) REFERENCES categories(id)
);


CREATE TABLE orders (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    order_number VARCHAR(50) UNIQUE NOT NULL,
    total_amount DECIMAL(10,2) NOT NULL,
    division_id INT,
    district_id INT,
    upazila_id INT,
    detailed_address TEXT NOT NULL,
    phone VARCHAR(20) NOT NULL,
    status ENUM('pending', 'confirmed', 'processing', 'shipped', 'delivered', 'cancelled') DEFAULT 'pending',
    payment_method VARCHAR(50) DEFAULT 'Cash on Delivery',
    order_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (division_id) REFERENCES divisions(id),
    FOREIGN KEY (district_id) REFERENCES districts(id),
    FOREIGN KEY (upazila_id) REFERENCES upazilas(id)
);


CREATE TABLE order_items (
    id INT PRIMARY KEY AUTO_INCREMENT,
    order_id INT,
    product_id INT,
    quantity INT NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    size VARCHAR(50),
    FOREIGN KEY (order_id) REFERENCES orders(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);


CREATE TABLE cart (
    id INT PRIMARY KEY AUTO_INCREMENT,
    user_id INT,
    product_id INT,
    quantity INT DEFAULT 1,
    size VARCHAR(50),
    added_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (product_id) REFERENCES products(id)
);


INSERT INTO categories (name, slug) VALUES
('Bangles', 'bangles'),
('Sarees', 'sarees'),
('Panjabi', 'panjabi'),
('Dress', 'dress'),
('Bags', 'bags');